
#include "config.h"
#include "config_helper.h"

#define KAKUTEF7HDV

#define F4
#define F745

//PORTS
#define SPI_PORTS \
  SPI1_PA5PA6PA7  \
  SPI2_PB13PB14PB15  \
  SPI4_PE2PE5PE6  \

#define USART_PORTS \
	USART1_PA10PA9 \
	USART2_PD6PD5 \
	USART3_PB11PB10 \
	USART4_PA1PA0 \
	USART6_PC7PC6 \
	USART7_PE7

//LEDS
#define LED_NUMBER 1
#define LED1PIN Pin_PIN_A2

#define BUZZER_PIN PIN_D15

//GYRO
#define MPU6XXX_SPI_PORT SPI_PORT4
#define MPU6XXX_NSS PIN_E4
// #define MPU6XXX_INT 
#define USE_DUMMY_I2C
#define SENSOR_ROTATE_90_CCW
#define GYRO_ID_1 0x68
#define GYRO_ID_2 0x73
#define GYRO_ID_3 0x78
#define GYRO_ID_4 0x71

//RADIO
#define RX_USART USART_PORT2
#define SOFTSPI_NONE

// OSD
#define ENABLE_OSD
#define MAX7456_SPI_PORT SPI_PORT0
#define MAX7456_NSS PIN_B12

//VOLTAGE DIVIDER
#define BATTERYPIN GPIO_Pin_PIN_C3
#define BATTERY_ADC_CHANNEL ADC_Channel_8

#ifndef VOLTAGE_DIVIDER_R1
#define VOLTAGE_DIVIDER_R1 10000
#endif

#ifndef VOLTAGE_DIVIDER_R2
#define VOLTAGE_DIVIDER_R2 1000
#endif

#ifndef ADC_REF_VOLTAGE
#define ADC_REF_VOLTAGE 3.3
#endif

// MOTOR PINS
#define MOTOR_PIN0 MOTOR_PIN_PB0
#define MOTOR_PIN1 MOTOR_PIN_PB1
#define MOTOR_PIN2 MOTOR_PIN_PE9
#define MOTOR_PIN3 MOTOR_PIN_PE11
#define MOTOR_PIN4 MOTOR_PIN_PC9
#define MOTOR_PIN5 MOTOR_PIN_PA3
